### ISSUE TITLE
Environments should have continuous action spaces

### ISSUE THREAD

**Issue by kevinmcareavey** [TSL-UOB/CAV-Gym#21]
In principle each environment has a continuous action space.

Currently, however, these continuous action spaces are discretised within the environment itself so that agents only have access to the discrete action space rather than the full continuous action space.

A better alternative is to expose the full continuous action space to agents, allowing them to discretise the action space if (or however) they wish.

**Comment by Abanoub-G** [comment]
Having a continuous action space is necessary to enable ego vehicles' controllers to be tested or used in CAV-Gym. Additionally, it should make the transfer of tests or experiments from the simple CAV-Gym environment to physics simulators, like CARLA, straight forward with minimal effort.

For this to be implemented, we need to be able to define way points in the continuous action space in the CAV-Gym environment. To follow the way points in the continuous action space, ideally one should be able to control vehicles (especially ego vehicle) through throttle and steering commands only.

**Comment by kevinmcareavey** [comment]
Agreed.

I imagine waypoints will be (internal) objectives for the agents such that the agent will need to (1) decide what points it wants to reach and (2) figure out how to reach those points (or a point within some boundary around each?) by controlling only throttle and steering angle.  The action space for a vehicle/pedestrian will be the set A = [t_min, t_max] * [s_min, s_max] where (t, s) \in A is a tuple specifying throttle value t and steering angle s.

Discretisation of the continuous action space equivalent to the current implementation can be achieved within the agents themselves, but precision errors will likely be an issue (e.g. over- or under-steering).

**Comment by kevinmcareavey** [comment]
Resolved: 212df26c3b74f4548584687eb9025c901c395600
