### ISSUE TITLE
Implement Frenet controller as agent

### ISSUE THREAD

**Issue by Abanoub-G** [TSL-UOB/CAV-Gym#23]
Created a new folder AV, which I think should contain our AV implementation for ease of transferring to other platforms (example Carla simulator), should we wish to do so.

The main script in there shows a simple example (very similar to what was provided by the Python robotics library), that we can start off with to integrate the Frenet optimiser with CAV-GYM. Variables specific to AV characteristics  can be found in frenet_optimal_trajectory.py.  

From an initial assessment, we hypothesized that the computational cost is high and will cause performance issues. Additionally, the for the AV to avoid agents in a timely manner using the Frenet optimiser, temporal predictions of the agents will be needed.

Thus, current tasks:
- enhancement of Frenet optimiser  performance
- integration of Frenet optimiser with agents temporal predictions.

**Comment by Abanoub-G** [comment]
Related issude #22

**Comment by kevinmcareavey** [comment]
Relevant code:

https://github.com/AtsushiSakai/PythonRobotics#optimal-trajectory-in-a-frenet-frame

https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py

**Comment by kevinmcareavey** [comment]
The Frenet controller has been implemented as an agent, but needs further optimisations to make it usable.

I consider this issue to be closed.
