### ISSUE TITLE
Traffic lights should be paired as pelican crossings

### ISSUE THREAD

**Issue by kevinmcareavey** [TSL-UOB/CAV-Gym#4]
The traffic light actor should be replaced with a pelican crossing actor associated with a given road at a given x-coordinate.  An agent can then control a pelican crossing rather than individual traffic lights.

**Comment by kevinmcareavey** [comment]
Feature is now supported: e2ce86bbcf7ec7e15774c20093908a2e7b72210b

**Comment by KerstinEder** [comment]
Excellent progress. I look forward to the update later this week. :)
